version: "3"

services:

    posts:
        build: ./posts
        # ports: 
        #     - "4000:4000"
        depends_on:
            - "events"
            - "moderation"

    comments:
        build: ./comments
        # ports: 
        #     - "4001:4001"
        depends_on: 
            - "events"
            - "moderation"
    
    query:
        build: ./query
        # ports: 
        #     - "4002:4002"
        depends_on:
            - "events"
            
    moderation:
        build: ./moderation
        # ports: 
        #     - "4003:4003"
        depends_on:
            - "events"

    events:
        build: ./events
        # ports: 
        #     - "4005:4005"
    
    client:
        build: ./client
        # ports:
        #     - "8000:8000"
        depends_on: 
            - "comments"
            - "events"
            - "moderation"
            - "posts"
            - "query"